export { default as Logo } from "../resource/image/logo.svg";
export { default as LogoWhite } from "../resource/image/logoWhite.svg";
export { default as wifi } from "../resource/image/wifi.png";
export { default as slide1 } from "../resource/image/slide1.png";
export { default as logo1 } from "../resource/image/logo11.png";
export { default as slide2 } from "../resource/image/slide2.svg";
export { default as product1 } from "../resource/image/phoneProduct.svg";
export { default as Iphone } from "../resource/image/iphone.svg";
export { default as Computer } from "../resource/image/Computer 1.svg";
export { default as Camera } from "../resource/image/Camera01 1.svg";
export { default as Phones } from "../resource/image/phone 1.svg";
export { default as Notebook } from "../resource/image/Notebook 1.svg";
export { default as A892 } from "./image/892 1.svg";
export { default as Brand_samsung } from "./image/brands/samsung.svg";
export { default as Brand_canon } from "./image/brands/canon.svg";
export { default as Brand_mi } from "./image/brands/mi.svg";
export { default as Brand_artel } from "./image/brands/artel.svg";
export { default as Brand_lg } from "./image/brands/lg.svg";